version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    restart: always
